config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  concern :access_requestable do
    post :request_access, on: :collection
    post :approve_access_request, on: :member
  end

  concern :awardable do
    post :toggle_award_emoji, on: :member
  end

  draw :sherlock
  draw :development
  draw :ci

  use_doorkeeper do
    controllers applications: 'oauth/applications',
                authorized_applications: 'oauth/authorized_applications',
                authorizations: 'oauth/authorizations'
  end

  namespace :oauth do
    scope path: 'geo', controller: :geo_auth, as: :geo do
      get 'auth'
      get 'callback'
      get 'logout'
    end
  end

  use_doorkeeper_openid_connect

  # Autocomplete
  get '/autocomplete/users' => 'autocomplete#users'
  get '/autocomplete/users/:id' => 'autocomplete#user'
  get '/autocomplete/projects' => 'autocomplete#projects'
  get '/autocomplete/project_groups' => 'autocomplete#project_groups'

  # Search
  get 'search' => 'search#show'
  get 'search/autocomplete' => 'search#autocomplete', as: :search_autocomplete

  # JSON Web Token
  get 'jwt/auth' => 'jwt#auth'

  # Health check
  get 'health_check(/:checks)' => 'health_check#index', as: :health_check

  scope path: '-' do
    get 'liveness' => 'health#liveness'
    get 'readiness' => 'health#readiness'
    resources :metrics, only: [:index]
    mount Peek::Railtie => '/peek'
  end

  # Koding route
  get 'koding' => 'koding#index'

  draw :api
  draw :sidekiq
  draw :help
  draw :snippets

  # Invites
  resources :invites, only: [:show], constraints: { id: /[A-Za-z0-9_-]+/ } do
    member do
      post :accept
      match :decline, via: [:get, :post]
    end
  end

  resources :sent_notifications, only: [], constraints: { id: /\h{32}/ } do
    member do
      get :unsubscribe
    end
  end

  # Spam reports
  resources :abuse_reports, only: [:new, :create]

  # Notification settings
  resources :notification_settings, only: [:create, :update]

  draw :import
  draw :uploads
  draw :explore
  draw :admin
  draw :profile
  draw :dashboard
  draw :group
  draw :user
  draw :project

  root to: "root#index"

  draw :test if Rails.env.test?

  get '*unmatched_route', to: 'application#route_not_found'
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::ApplicationController
  before_action :project, only: [:show, :transfer, :repository_check]
  before_action :group, only: [:show, :transfer]

  def index
    params[:sort] ||= 'latest_activity_desc'
    @projects = Project.with_statistics
    @projects = @projects.in_namespace(params[:namespace_id]) if params[:namespace_id].present?
    @projects = @projects.where(visibility_level: params[:visibility_level]) if params[:visibility_level].present?
    @projects = @projects.with_push if params[:with_push].present?
    @projects = @projects.abandoned if params[:abandoned].present?
    @projects = @projects.where(last_repository_check_failed: true) if params[:last_repository_check_failed].present?
    @projects = @projects.non_archived unless params[:archived].present?
    @projects = @projects.personal(current_user) if params[:personal].present?
    @projects = @projects.search(params[:name]) if params[:name].present?
    @projects = @projects.sort(@sort = params[:sort])
    @projects = @projects.includes(:namespace).order("namespaces.path, projects.name ASC").page(params[:page])

    respond_to do |format|
      format.html
      format.json do
        render json: {
          html: view_to_html_string("admin/projects/_projects", locals: { projects: @projects })
        }
      end
    end
  end

  def show
    if @group
      @group_members = @group.members.order("access_level DESC").page(params[:group_members_page])
    end

    @project_members = @project.members.page(params[:project_members_page])
    @requesters = AccessRequestsFinder.new(@project).execute(current_user)
  end

  def transfer
    namespace = Namespace.find_by(id: params[:new_namespace_id])
    ::Projects::TransferService.new(@project, current_user, params.dup).execute(namespace)

    @project.reload
    redirect_to admin_project_path(@project)
  end

  def repository_check
    RepositoryCheck::SingleRepositoryWorker.perform_async(@project.id)

    redirect_to(
      admin_project_path(@project),
      notice: 'Repository check was triggered.'
    )
  end

  protected

  def project
    @project = Project.find_by_full_path(
      [params[:namespace_id], '/', params[:id]].join('')
    )
    @project || render_404
  end

  def group
    @group ||= @project.group
  end
end

app/controllers/dashboard/projects_controller.rb
class Dashboard::ProjectsController < Dashboard::ApplicationController
  include ParamsBackwardCompatibility

  before_action :set_non_archived_param
  before_action :default_sorting

  def index
    @projects = load_projects(params.merge(non_public: true)).page(params[:page])

    respond_to do |format|
      format.html
      format.atom do
        load_events
        render layout: 'xml.atom'
      end
      format.json do
        render json: {
          html: view_to_html_string("dashboard/projects/_projects", locals: { projects: @projects })
        }
      end
    end
  end

  def starred
    @projects = load_projects(params.merge(starred: true))
      .includes(:forked_from_project, :tags).page(params[:page])

    @groups = []

    respond_to do |format|
      format.html
      format.json do
        render json: {
          html: view_to_html_string("dashboard/projects/_projects", locals: { projects: @projects })
        }
      end
    end
  end

  private

  def default_sorting
    params[:sort] ||= 'latest_activity_desc'
    @sort = params[:sort]
  end

  def load_projects(finder_params)
    ProjectsFinder.new(params: finder_params, current_user: current_user)
      .execute.includes(:route, namespace: :route)
  end

  def load_events
    @events = Event.in_projects(load_projects(params.merge(non_public: true)))
    @events = event_filter.apply_filter(@events).with_associations
    @events = @events.limit(20).offset(params[:offset] || 0)
  end
end

app/controllers/ee/projects/boards_controller.rb
module EE
  module Projects
    module BoardsController
      extend ActiveSupport::Concern
      prepended do
        before_action :check_multiple_issue_boards_available!, only: [:create]
        before_action :authorize_admin_board!, only: [:create, :update, :destroy]
        before_action :find_board, only: [:update, :destroy]
      end

      def create
        board = ::Boards::CreateService.new(project, current_user, board_params).execute

        respond_to do |format|
          format.json do
            if board.valid?
              render json: serialize_as_json(board)
            else
              render json: board.errors, status: :unprocessable_entity
            end
          end
        end
      end

      def update
        service = ::Boards::UpdateService.new(project, current_user, board_params)

        service.execute(@board)

        respond_to do |format|
          format.json do
            if @board.valid?
              render json: serialize_as_json(@board)
            else
              render json: @board.errors, status: :unprocessable_entity
            end
          end
        end
      end

      def destroy
        service = ::Boards::DestroyService.new(project, current_user)
        service.execute(@board)

        respond_to do |format|
          format.html { redirect_to project_boards_path(@project), status: 302 }
        end
      end

      private

      def authorize_admin_board!
        return render_404 unless can?(current_user, :admin_board, project)
      end

      def board_params
        params.require(:board).permit(:name, :milestone_id)
      end

      def find_board
        @board = project.boards.find(params[:id])
      end

      def serialize_as_json(resource)
        resource.as_json(
          only: [:id, :name],
          include: {
            milestone: { only: [:id, :title] }
          }
        )
      end
    end
  end
end

app/controllers/ee/projects/issues_controller.rb
module EE
  module Projects
    module IssuesController
      extend ActiveSupport::Concern

      prepended do
        before_action :check_export_issues_available!, only: [:export_csv]
      end

      def export_csv
        ExportCsvWorker.perform_async(current_user.id, project.id, filter_params)

        index_path = project_issues_path(project)
        redirect_to(index_path, notice: "Your CSV export has started. It will be emailed to #{current_user.notification_email} when complete.")
      end

      def issue_params_attributes
        attrs = super
        attrs.unshift(:weight) if project.feature_available?(:issue_weights)

        attrs
      end

      def filter_params
        params = super
        params.reject! { |key| key == 'weight' } unless project.feature_available?(:issue_weights)

        params
      end
    end
  end
end

app/controllers/ee/projects/merge_requests/application_controller.rb
module EE
  module Projects
    module MergeRequests
      module ApplicationController
        extend ActiveSupport::Concern

        private

        def set_suggested_approvers
          if @merge_request.requires_approve?
            @suggested_approvers = ::Gitlab::AuthorityAnalyzer.new(
              @merge_request,
              @merge_request.author || current_user
            ).calculate(@merge_request.approvals_required)
          end
        end

        def merge_request_params
          clamp_approvals_before_merge(super)
        end

        def merge_request_params_attributes
          attrs = super.push(
            :approvals_before_merge,
            :approver_group_ids,
            :approver_ids
          )
          attrs << :squash if project.feature_available?(:merge_request_squash)

          attrs
        end

        # If the number of approvals is not greater than the project default, set to
        # nil, so that we fall back to the project default. If it's not set, we can
        # let the normal update logic handle this.
        def clamp_approvals_before_merge(mr_params)
          return mr_params unless mr_params[:approvals_before_merge]

          target_project = @project.forked_from_project if @project.id.to_s != mr_params[:target_project_id]
          target_project ||= @project

          if mr_params[:approvals_before_merge].to_i <= target_project.approvals_before_merge
            mr_params[:approvals_before_merge] = nil
          end

          mr_params
        end
      end
    end
  end
end

app/controllers/ee/projects/merge_requests/creations_controller.rb
module EE
  module Projects
    module MergeRequests
      module CreationsController
        extend ActiveSupport::Concern

        private

        def define_new_vars
          super
          set_suggested_approvers
        end
      end
    end
  end
end

app/controllers/ee/projects/merge_requests_controller.rb
module EE
  module Projects
    module MergeRequestsController
      extend ActiveSupport::Concern

      prepended do
        before_action :check_merge_request_rebase_available!, only: [:rebase]
      end

      def rebase
        return access_denied! unless @merge_request.can_be_merged_by?(current_user)

        RebaseWorker.perform_async(@merge_request.id, current_user.id)

        render nothing: true, status: 200
      end

      def approve
        unless @merge_request.can_approve?(current_user)
          return render_404
        end

        ::MergeRequests::ApprovalService
          .new(project, current_user)
          .execute(@merge_request)

        render_approvals_json
      end

      def approvals
        render_approvals_json
      end

      def unapprove
        if @merge_request.has_approved?(current_user)
          ::MergeRequests::RemoveApprovalService
            .new(project, current_user)
            .execute(@merge_request)
        end

        render_approvals_json
      end

      protected

      def define_edit_vars
        super

        set_suggested_approvers
      end

      def render_approvals_json
        respond_to do |format|
          format.json do
            entity = ::API::Entities::MergeRequestApprovals.new(@merge_request, current_user: current_user)
            render json: entity
          end
        end
      end

      def merge_params_attributes
        attrs = super
        attrs << :squash if project.feature_available?(:merge_request_squash)

        attrs
      end
    end
  end
end

app/controllers/ee/projects/settings/repository_controller.rb
module EE
  module Projects
    module Settings
      module RepositoryController
        extend ActiveSupport::Concern

        prepended do
          before_action :push_rule, only: [:show]
          before_action :remote_mirror, only: [:show]
        end

        private

        def push_rule
          return unless project.feature_available?(:push_rules)

          project.create_push_rule unless project.push_rule
          @push_rule = project.push_rule
        end

        def remote_mirror
          @remote_mirror = @project.remote_mirrors.first_or_initialize
        end

        def acces_levels_options
          super.merge(
            selected_merge_access_levels: @protected_branch.merge_access_levels.map { |access_level| access_level.user_id || access_level.access_level },
            selected_push_access_levels: @protected_branch.push_access_levels.map { |access_level| access_level.user_id || access_level.access_level },
            selected_create_access_levels: @protected_tag.create_access_levels.map { |access_level| access_level.user_id || access_level.access_level }
          )
        end

        def load_gon_index
          super

          gon.push(current_project_id: @project.id) if @project
        end
      end
    end
  end
end

app/controllers/ee/projects/variables_controller.rb
module EE
  module Projects
    module VariablesController
      extend ActiveSupport::Concern

      def variable_params_attributes
        attrs = super

        attrs.unshift(:environment_scope) if
            project.feature_available?(:variable_environment_scope)

        attrs
      end
    end
  end
end

app/controllers/explore/projects_controller.rb
class Explore::ProjectsController < Explore::ApplicationController
  include ParamsBackwardCompatibility

  before_action :set_non_archived_param

  def index
    params[:sort] ||= 'latest_activity_desc'
    @sort = params[:sort]
    @projects = load_projects.page(params[:page])

    respond_to do |format|
      format.html
      format.json do
        render json: {
          html: view_to_html_string("dashboard/projects/_projects", locals: { projects: @projects })
        }
      end
    end
  end

  def trending
    params[:trending] = true
    @sort = params[:sort]
    @projects = load_projects.page(params[:page])

    respond_to do |format|
      format.html
      format.json do
        render json: {
          html: view_to_html_string("dashboard/projects/_projects", locals: { projects: @projects })
        }
      end
    end
  end

  def starred
    @projects = load_projects.reorder('star_count DESC').page(params[:page])

    respond_to do |format|
      format.html
      format.json do
        render json: {
          html: view_to_html_string("dashboard/projects/_projects", locals: { projects: @projects })
        }
      end
    end
  end

  private

  def load_projects
    ProjectsFinder.new(current_user: current_user, params: params)
      .execute.includes(:route, namespace: :route)
  end
end

app/controllers/projects/approver_groups_controller.rb
class Projects::ApproverGroupsController < Projects::ApplicationController
  before_action :authorize_for_subject!

  def destroy
    subject.approver_groups.find(params[:id]).destroy

    redirect_back_or_default(default: { action: 'index' })
  end

  private

  def authorize_for_subject!
    access_denied! unless can?(current_user, :update_approvers, subject)
  end

  def subject
    @subject ||=
      if params[:merge_request_id]
        project.merge_requests.find_by!(iid: params[:merge_request_id])
      else
        project
      end
  end
end

app/controllers/projects/approvers_controller.rb
class Projects::ApproversController < Projects::ApplicationController
  before_action :authorize_for_subject!

  def destroy
    subject.approvers.find(params[:id]).destroy

    redirect_back_or_default(default: { action: 'index' })
  end

  private

  def authorize_for_subject!
    access_denied! unless can?(current_user, :update_approvers, subject)
  end

  def subject
    @subject ||=
      if params[:merge_request_id]
        project.merge_requests.find_by!(iid: params[:merge_request_id])
      else
        project
      end
  end
end

app/controllers/projects/audit_events_controller.rb
class Projects::AuditEventsController < Projects::ApplicationController
  before_action :authorize_admin_project!

  layout 'project_settings'

  def index
    @events = project.audit_events.page(params[:page])
  end
end

app/views/projects/cycle_analytics/_empty_stage.html.haml
.empty-stage-container
  .empty-stage
    .icon-no-data
      = custom_icon ('icon_no_data')
    %h4 {{ __('We don\'t have enough data to show this stage.') }}
    %p
      {{currentStage.emptyStageText}}

app/views/projects/cycle_analytics/_no_access.html.haml
.no-access-stage-container
  .no-access-stage
    .icon-lock
      = custom_icon ('icon_lock')
    %h4 {{ __('You need permission.') }}
    %p
      {{ __('Want to see the data? Please ask an administrator for access.') }}

app/views/projects/cycle_analytics/_overview.html.haml
.cycle-analytics-overview
  .container
    .row
      .col-md-10.col-md-offset-1
        .row.overview-details
          .col-md-6.overview-text
            %h4 Introducing Cycle Analytics
            %p
              Cycle Analytics gives an overview of how much time it takes to go from idea to production in your project.
              To set up CA, you must first define a production environment by setting up your CI and then deploy to production.
            %p
              %a.btn{ href: help_page_path('user/project/cycle_analytics'), target: '_blank' } Read more
          .col-md-6.overview-image
            %span.overview-icon
              = custom_icon ('icon_cycle_analytics_overview')

app/views/projects/cycle_analytics/show.html.haml
- @no_container = true
- page_title "Cycle Analytics"
- if show_new_nav?
  - add_to_breadcrumbs("Project", project_path(@project))
- content_for :page_specific_javascripts do
  = page_specific_javascript_bundle_tag('common_vue')
  = page_specific_javascript_bundle_tag('cycle_analytics')

= render "projects/head"

#cycle-analytics{ class: container_class, "v-cloak" => "true", data: { request_path: project_cycle_analytics_path(@project) } }
  - if @cycle_analytics_no_data
    .landing.content-block{ "v-if" => "!isOverviewDialogDismissed" }
      %button.dismiss-button{ type: 'button', 'aria-label': 'Dismiss Cycle Analytics introduction box' }
        = icon("times", "@click" => "dismissOverviewDialog()")
      .svg-container
        = custom_icon('icon_cycle_analytics_splash')
      .inner-content
        %h4
          {{ __('Introducing Cycle Analytics') }}
        %p
          {{ __('Cycle Analytics gives an overview of how much time it takes to go from idea to production in your project.') }}
        %p
          = link_to _('Read more'), help_page_path('user/project/cycle_analytics'), target: '_blank', class: 'btn'
  = icon("spinner spin", "v-show" => "isLoading")
  .wrapper{ "v-show" => "!isLoading && !hasError" }
    .panel.panel-default
      .panel-heading
        {{ __('Pipeline Health') }}
      .content-block
        .container-fluid
          .row
            .col-sm-3.col-xs-12.column{ "v-for" => "item in state.summary" }
              %h3.header {{ item.value }}
              %p.text {{ item.title }}
            .col-sm-3.col-xs-12.column
              .dropdown.inline.js-ca-dropdown
                %button.dropdown-menu-toggle{ "data-toggle" => "dropdown", :type => "button" }
                  %span.dropdown-label {{ n__('Last %d day', 'Last %d days', 30) }}
                  %i.fa.fa-chevron-down
                %ul.dropdown-menu.dropdown-menu-align-right
                  %li
                    %a{ "href" => "#", "data-value" => "30" }
                      {{ n__('Last %d day', 'Last %d days', 30) }}
                  %li
                    %a{ "href" => "#", "data-value" => "90" }
                      {{ n__('Last %d day', 'Last %d days', 90) }}
    .stage-panel-container
      .panel.panel-default.stage-panel
        .panel-heading
          %nav.col-headers
            %ul
              %li.stage-header
                %span.stage-name
                  {{ s__('ProjectLifecycle|Stage') }}
                %i.has-tooltip.fa.fa-question-circle{ "data-placement" => "top", title: _("The phase of the development lifecycle."), "aria-hidden" => "true" }
              %li.median-header
                %span.stage-name
                  {{ __('Median') }}
                %i.has-tooltip.fa.fa-question-circle{ "data-placement" => "top", title: _("The value lying at the midpoint of a series of observed values. E.g., between 3, 5, 9, the median is 5. Between 3, 5, 7, 8, the median is (5+7)/2 = 6."), "aria-hidden" => "true" }
              %li.event-header
                %span.stage-name
                  {{ currentStage ? __(currentStage.legend) : __('Related Issues') }}
                %i.has-tooltip.fa.fa-question-circle{ "data-placement" => "top", title: _("The collection of events added to the data gathered for that stage."), "aria-hidden" => "true" }
              %li.total-time-header
                %span.stage-name
                  {{ __('Total Time') }}
                %i.has-tooltip.fa.fa-question-circle{ "data-placement" => "top", title: _("The time taken by each data entry gathered by that stage."), "aria-hidden" => "true" }
        .stage-panel-body
          %nav.stage-nav
            %ul
              %li.stage-nav-item{ ':class' => '{ active: stage.active }', '@click' => 'selectStage(stage)', "v-for" => "stage in state.stages" }
                .stage-nav-item-cell.stage-name
                  {{ stage.title }}
                .stage-nav-item-cell.stage-median
                  %template{ "v-if" => "stage.isUserAllowed" }
                    %span{ "v-if" => "stage.value" }
                      {{ stage.value }}
                    %span.stage-empty{ "v-else" => true }
                      {{ __('Not enough data') }}
                  %template{ "v-else" => true }
                    %span.not-available
                      {{ __('Not available') }}
          .section.stage-events
            %template{ "v-if" => "isLoadingStage" }
              = icon("spinner spin")
            %template{ "v-if" => "currentStage && !currentStage.isUserAllowed" }
              = render partial: "no_access"
            %template{ "v-else" => true }
              %template{ "v-if" => "isEmptyStage && !isLoadingStage" }
                = render partial: "empty_stage"
              %template{ "v-if" => "state.events.length && !isLoadingStage && !isEmptyStage" }
                %component{ ":is" => "currentStage.component", ":stage" => "currentStage", ":items" => "state.events" }